import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { catalogApi } from '../../api'
import type { Book, ContentType, FeedbackRequest, Video } from '../../types'

export function StudentDetailPage() {
  const { type, id } = useParams(); const contentType = type === 'video' ? 'VIDEO' : 'BOOK'; const numericId = Number(id); const [content, setContent] = useState<Book | Video>(); const [mediaUrl, setMediaUrl] = useState(''); const [message, setMessage] = useState(''); const [feedback, setFeedback] = useState({ rating: 5, content: '' })
  useEffect(() => { (contentType === 'BOOK' ? catalogApi.book(numericId) : catalogApi.video(numericId)).then((response) => setContent(response.data.data)).catch(() => setMessage('Không thể tải nội dung.')) }, [contentType, numericId])
  const openMedia = async () => { try { if (contentType === 'BOOK') { const response = await catalogApi.bookDownloadUrl(numericId); await catalogApi.bookDownloaded(numericId); window.open(response.data.data.downloadUrl, '_blank', 'noopener,noreferrer'); setMessage('Đường dẫn tải đã được mở trong tab mới.') } else { const response = await catalogApi.videoStreamUrl(numericId); await catalogApi.videoViewed(numericId); setMediaUrl(response.data.data.streamingUrl) } } catch { setMessage('Chưa thể mở nội dung. Vui lòng thử lại.') } }
  const sendFeedback = async (event: React.FormEvent) => { event.preventDefault(); const payload: FeedbackRequest = { targetType: contentType, targetId: numericId, rating: feedback.rating, content: feedback.content }; try { await catalogApi.feedback(payload); setMessage('Cảm ơn bạn, feedback đã được gửi.'); setFeedback({ rating: 5, content: '' }) } catch { setMessage('Chưa thể gửi feedback. Vui lòng thử lại.') } }
  if (!content) return <main className="detail-page"><Link to="/student" className="back-link">← Quay lại thư viện</Link><p>{message || 'Đang tải...'}</p></main>
  return <main className="detail-page"><Link to="/student" className="back-link">← Quay lại thư viện</Link><div className="detail-layout"><article><div className={`detail-art ${contentType.toLowerCase()}`}><span>{contentType === 'BOOK' ? 'READING ROOM' : 'WATCH ROOM'}</span><strong>{contentType === 'BOOK' ? 'B' : 'V'}</strong></div><span className="eyebrow">{content.categoryName || 'CLOUD CAMPUS'}</span><h1>{content.title}</h1><p className="detail-description">{content.description || 'Một tài liệu được tuyển chọn cho quá trình học tập của bạn.'}</p><button className="button button-primary" onClick={openMedia}>{contentType === 'BOOK' ? 'Tải tài liệu' : 'Xem video'} <span aria-hidden="true">↗</span></button>{mediaUrl && <video className="video-player" controls autoPlay src={mediaUrl}>Trình duyệt không hỗ trợ phát video.</video>}{message && <p className="status-message" role="status">{message}</p>}</article><form className="feedback-panel" onSubmit={sendFeedback}><span className="eyebrow">LEAVE A NOTE</span><h2>Chia sẻ cảm nhận</h2><p className="muted">Feedback của bạn giúp thư viện tốt hơn.</p><label>Đánh giá<select value={feedback.rating} onChange={(event) => setFeedback({ ...feedback, rating: Number(event.target.value) })}>{[5, 4, 3, 2, 1].map((rating) => <option key={rating} value={rating}>{rating} / 5</option>)}</select></label><label>Lời nhắn<textarea value={feedback.content} onChange={(event) => setFeedback({ ...feedback, content: event.target.value })} required minLength={3} rows={5} placeholder="Điều gì hữu ích với bạn?" /></label><button className="button button-secondary" type="submit">Gửi feedback</button></form></div></main>
}