import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { catalogApi } from '../../api'
import { useAuth } from '../../auth'
import type { Book, Category, Video } from '../../types'

export function StudentHomePage() {
  const { user, logout } = useAuth(); const [params, setParams] = useSearchParams(); const query = params.get('q') || ''; const [search, setSearch] = useState(query); const [category, setCategory] = useState<number>(); const [categories, setCategories] = useState<Category[]>([]); const [books, setBooks] = useState<Book[]>([]); const [videos, setVideos] = useState<Video[]>([]); const [error, setError] = useState('')
  useEffect(() => { catalogApi.categories().then((response) => setCategories(response.data.data)).catch(() => setError('Chưa tải được danh mục.')) }, [])
  useEffect(() => { Promise.all([catalogApi.books(category, query), catalogApi.videos(category, query)]).then(([bookResponse, videoResponse]) => { setBooks(bookResponse.data.data); setVideos(videoResponse.data.data) }).catch(() => setError('Chưa tải được nội dung.')) }, [category, query])
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); setParams(search ? { q: search } : {}) }
  return <main className="student-portal student-shell"><header className="student-topbar"><Link className="student-brand" to="/student"><span className="student-brand-mark">CC</span> Cloud Campus</Link><nav className="student-nav"><span className="student-welcome">Xin chào, {user?.fullName}</span><button className="student-text-button" onClick={logout}>Đăng xuất</button></nav></header><section className="student-hero"><div><span className="student-eyebrow">THƯ VIỆN HỌC TẬP CỦA BẠN</span><h1>Tìm điều<br /><em>đáng học.</em></h1><p className="student-hero-copy">Khám phá sách và video được tuyển chọn cho hành trình tiếp theo của bạn.</p></div><form className="student-search-box" onSubmit={submitSearch}><label className="student-search-label" htmlFor="search">Bạn muốn học gì hôm nay?</label><div className="student-search-row"><input id="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm theo tên, chủ đề..." /><button className="student-button student-button-primary" type="submit">Tìm kiếm</button></div></form></section><section><div className="student-section-heading"><div><span className="student-eyebrow">KHÁM PHÁ / {books.length + videos.length} NỘI DUNG</span><h2>Thư viện của bạn</h2></div><div className="student-category-filter"><button className={!category ? 'active' : ''} onClick={() => setCategory(undefined)}>Tất cả</button>{categories.map((item) => <button className={category === item.id ? 'active' : ''} key={item.id} onClick={() => setCategory(item.id)}>{item.name}</button>)}</div></div>{error && <p className="student-error">{error}</p>}<div className="student-content-grid">{books.map((book) => <ContentCard key={`book-${book.id}`} type="book" id={book.id} title={book.title} meta={book.author || 'Tài liệu học tập'} category={book.categoryName} />)}{videos.map((video) => <ContentCard key={`video-${video.id}`} type="video" id={video.id} title={video.title} meta={formatDuration(video.durationSeconds)} category={video.categoryName} />)}</div>{!books.length && !videos.length && <p className="student-empty">Không có nội dung phù hợp. Thử một từ khóa khác nhé.</p>}</section></main>
}

function ContentCard({ type, id, title, meta, category }: { type: 'book' | 'video'; id: number; title: string; meta: string; category?: string }) { return <Link className="student-content-card" to={`/student/${type}/${id}`}><div className={`student-card-art ${type}`}><span>{type === 'book' ? 'ĐỌC' : 'XEM'}</span><strong>{type === 'book' ? 'B' : 'V'}</strong></div><div className="student-card-copy"><span className="student-card-category">{category || 'Cloud Campus'}</span><h3>{title}</h3><p>{meta}</p><span className="student-card-arrow">Xem chi tiết <span aria-hidden="true">↗</span></span></div></Link> }
function formatDuration(seconds?: number) { if (!seconds) return 'Video bài giảng'; return `${Math.floor(seconds / 60)} phút ${seconds % 60} giây` }